title: learning-notes
author: Pratyush Nalam
email: pratyushnalam@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Notes that I take down from the various courses I take, books I read, and podcasts
  I listen to will be available here.

twitter_username: pratnala
github_username:  pratnala

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

collections:
  moocs:
    output: true
  podcasts:
    output: true

podcast-categories: ['a16z', 'developer-tea', 'how-i-built-this', 'optimize', 'the-tim-ferris-show']
mooc-categories: ['feelthelearn-product-manager']

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - moocs.md
 - podcasts.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
